### ISSUE TITLE
Adopt this crate

### ISSUE THREAD

**Issue by hasufell** [hasufell/rust-libnotify#2]
I want to adop this crate.

**Comment by crumblingstatue** [comment]
Do you have a crates.io account? You need one in order for me to transfer ownership to you.

**Comment by hasufell** [comment]
I am logged in with github there

**Comment by crumblingstatue** [comment]
Alright, I added you as owner for both crates on crates.io. Do you need anything else?

**Comment by hasufell** [comment]
I don't know, which repository will be used? Should I create a fork?

**Comment by crumblingstatue** [comment]
You could create a fork, but I can also transfer ownership of this repository to you.

**Comment by hasufell** [comment]
Whatever you think is best

**Comment by crumblingstatue** [comment]
Alright, I'll transfer ownership. You should get a message about it in your dashboard (or something, I forgot).

**Comment by crumblingstatue** [comment]
Alright, thanks for adopting!

**Comment by hasufell** [comment]
thanks!
